server:
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:clientes;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    data: classpath:/db/h2/import.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  jackson:
    time-zone: America/Santiago
    locale: es_CL
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #  data:
#    web:
#      pageable:
#        size-parameter: size
#        page-parameter: page
#        default-page-size: 10
#        one-indexed-parameters: false
#        max-page-size: 2000
#        prefix:
#        qualifier-delimiter: _
  liquibase:
    enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
#  config: classpath:log4j/config/log4j2.yml